// metronic_react_v8.2.3/react/metronic_react_v8.2.3_demo5/src/app/modules/apps/dev/components/Question.tsx


import React, {useState} from 'react'
import {KTIcon} from '../../../../../_metronic/helpers'
import {TextFormatting} from './partials/TextFormatting'
import {EnableSidebar} from '../../../../../_metronic/layout/core'
import {Replies} from './partials/Replies'
import { Toolbar } from '../../../../../_metronic/layout/components/toolbar/Toolbar'
import { Content } from '../../../../../_metronic/layout/components/Content'

const Question: React.FC = () => {
  const [textFormatting, setTextFormatting] = useState<boolean>(false)

  return (
    <>
      <Toolbar />
      <Content>
        <EnableSidebar>
          <div className='mb-0'>
            <div className='d-flex align-items-center mb-9'>
              <h1 className='fs-2x fw-bolder text-gray-900 mb-0 me-1'>
                How to use Metronic with Laravel Framework ?
              </h1>

              <div className='d-flex align-items-center'>
                <span className='ms-1' data-bs-toggle='tooltip' title='User replied'>
                  <KTIcon iconName='check-circle' className='text-success fs-1' />
                </span>
              </div>
            </div>

            <div className='fs-4 fw-normal text-gray-800 mb-10'>
              <p>Hi Keenthemes,</p>

              <p>
                I’ve been doing some ajax request, to populate a inside drawer, the content of that
                drawer has a sub menu, that you are using in list and all card toolbar.
              </p>

              <p>
                But they are not displaying, since it is an ajax, I tried “KTApp.init();” but didn’t
                work (worked for Tooltips sure, but not Menu).
              </p>

              <p>Anyway to Re-init those https://ibb.co/gysPGpx Menu. ?</p>

              <p>Thank you.</p>
            </div>

            <div className='d-flex flex-stack flex-wrap'>
              <div className='d-flex align-items-center py-1'>
                <div className='symbol symbol-35px me-2'>
                  <div className='symbol-label bg-light-success fs-3 fw-bold text-success text-uppercase'>
                    j
                  </div>
                </div>

                <div className='d-flex flex-column align-items-start justify-content-center'>
                  <span className='text-gray-800 fs-7 fw-bold lh-1 mb-2'>James Hunt</span>
                  <span className='text-muted fs-8 fw-bold lh-1'>24 minutes ago</span>
                </div>
              </div>

              <div className='d-flex align-items-center py-1'>
                <a
                  href='#answers'
                  data-kt-scroll-toggle='true'
                  className='btn btn-sm btn-outline btn-outline-dashed btn-outline-default px-4 me-2'
                >
                  12 Answers
                </a>

                <a
                  href="<?php echo Theme::getPageUrl('apps/devs/tag')?>"
                  className='btn btn-sm btn-light px-4 me-2'
                >
                  Laravel
                </a>

                <a
                  href="<?php echo Theme::getPageUrl('apps/devs/tag')?>"
                  className='btn btn-sm btn-light px-4 me-2'
                >
                  Metronic
                </a>

                <a
                  href='#'
                  className='btn btn-sm btn-icon btn-light me-2'
                  data-bs-toggle='tooltip'
                  title='Save for your future reference'
                  data-bs-dismiss='click'
                >
                  <KTIcon iconName='save-2' className='fs-2' />
                </a>

                <a
                  href='#'
                  className='btn btn-sm btn-flex btn-light px-4'
                  data-bs-toggle='tooltip'
                  title='Upvote this question'
                  data-bs-dismiss='click'
                >
                  23
                  <KTIcon iconName='black-right' className='fs-7 ms-1 me-1' />
                </a>
              </div>
            </div>
          </div>

          <div className='separator separator-dashed border-gray-300 mt-8 mb-10'></div>

          <form id='kt_devs_reply_form' className='form mb-10'>
            <div className='form-group mb-2'>
              <textarea
                name='comment'
                className='form-control'
                rows={6}
                placeholder='Your reply here..'
                maxLength={1000}
                data-kt-autosize='true'
              />
            </div>

            <div className='d-flex align-items-center justify-content-between py-2 mb-5'>
              <div
                onClick={() => {
                  setTextFormatting(!textFormatting)
                }}
                className='text-primary fs-base fw-bold cursor-pointer'
              >
                Text formatting options
              </div>

              <button className='btn btn-primary fw-bolder' data-kt-action='submit'>
                Submit
              </button>
            </div>

            {textFormatting && <TextFormatting />}
          </form>
          <Replies />
        </EnableSidebar>
      </Content>
    </>
    
  )
}

export {Question}

// metronic_vue_v8.2.3/vue/metronic_vue_v8.2.3_demo5/src/views/apps/devs/Question.vue
<template>
  <!--begin::Question-->
  <div class="mb-0">
    <!--begin::Head-->
    <div class="d-flex align-items-center mb-9">
      <!--begin::Title-->
      <h1 class="fs-2x fw-bold text-gray-900 mb-0 me-1">
        How to use Metronic with Laravel Framework ?
      </h1>
      <!--end::Title-->

      <!--begin::Icons-->
      <div class="d-flex align-items-center">
        <span class="ms-1" data-bs-toggle="tooltip" title="User replied">
          <KTIcon icon-name="check-circle" icon-class="text-success fs-1" />
        </span>
      </div>
      <!--end::Icons-->
    </div>
    <!--end::Head-->

    <!--begin::Question-->
    <div class="fs-4 fw-normal text-gray-800 mb-10">
      <p>Hi Keenthemes,</p>

      <p>
        I’ve been doing some ajax request, to populate a inside drawer, the
        content of that drawer has a sub menu, that you are using in list and
        all card toolbar.
      </p>

      <p>
        But they are not displaying, since it is an ajax, I tried
        “KTApp.init();” but didn’t work (worked for Tooltips sure, but not
        Menu).
      </p>

      <p>Anyway to Re-init those https://ibb.co/gysPGpx Menu. ?</p>

      <p>Thank you.</p>
    </div>
    <!--end::Question-->

    <!--begin::Foot-->
    <div class="d-flex flex-stack flex-wrap">
      <!--begin::Author-->
      <div class="d-flex align-items-center py-1">
        <!--begin::Symbol-->
        <div class="symbol symbol-35px me-2">
          <div
            class="symbol-label bg-light-success fs-3 fw-semibold text-success text-uppercase"
          >
            j
          </div>
        </div>
        <!--end::Symbol-->

        <!--begin::Name-->
        <div
          class="d-flex flex-column align-items-start justify-content-center"
        >
          <span class="text-gray-800 fs-7 fw-semibold lh-1 mb-2"
            >James Hunt</span
          >
          <span class="text-muted fs-8 fw-semibold lh-1">24 minutes ago</span>
        </div>
        <!--end::Name-->
      </div>
      <!--end::Author-->

      <!--begin::Info-->
      <div class="d-flex align-items-center py-1">
        <a
          href="#answers"
          data-kt-scroll-toggle="true"
          class="btn btn-sm btn-outline btn-outline-dashed btn-outline-default px-4 me-2"
        >
          12 Answers
        </a>

        <a href="#" class="btn btn-sm btn-light px-4 me-2"> Laravel </a>

        <a href="#>" class="btn btn-sm btn-light px-4 me-2"> Metronic </a>

        <a
          href="#"
          class="btn btn-sm btn-icon btn-light me-2"
          data-bs-toggle="tooltip"
          title="Save for your future reference"
          data-bs-dismiss="click"
        >
          <KTIcon icon-name="save-2" icon-class="fs-2" />
        </a>

        <a
          href="#"
          class="btn btn-sm btn-flex btn-light px-4"
          data-bs-toggle="tooltip"
          title="Upvote this question"
          data-bs-dismiss="click"
        >
          23
          <KTIcon icon-name="black-right" icon-class="fs-7 ms-1 me-1" />
        </a>
      </div>
      <!--end::Info-->
    </div>
    <!--end::Foot-->
  </div>
  <!--end::Question-->

  <!--begin::Separator-->
  <div class="separator separator-dashed border-gray-300 mt-8 mb-10"></div>
  <!--end::Separator-->

  <!--begin:Reply Form-->
  <form id="kt_devs_reply_form" class="form mb-10" action="#">
    <!--begin::Input group-->
    <div class="form-group mb-2">
      <textarea
        name="comment"
        class="form-control"
        rows="6"
        placeholder="Your reply here.."
        maxlength="1000"
        data-kt-autosize="true"
      ></textarea>
    </div>
    <!--end::Input group-->

    <!--begin::Action-->
    <div class="d-flex align-items-center justify-content-between py-2 mb-5">
      <!--begin::Formating toggle-->
      <div
        class="text-primary fs-base fw-semibold cursor-pointer"
        data-bs-toggle="collapse"
        data-bs-target="#kt_devs_ask_formatting"
      >
        Text formatting options
      </div>
      <!--end::Formating toggle-->

      <!--begin::Submit-->
      <button class="btn btn-primary fw-bold" data-kt-action="submit">
        Submit
      </button>
      <!--end::Submit-->
    </div>
    <!--end::Action-->

    <TextFormatting />
  </form>
  <!--end:Reply Form-->

  <Replies />
</template>

<script lang="ts">
import { getAssetPath } from "@/core/helpers/assets";
import { defineComponent, onMounted, onUnmounted } from "vue";
import TextFormatting from "@/components/devs/TextFormatting.vue";
import LayoutService from "@/core/services/LayoutService";
import Replies from "@/components/devs/Replies.vue";
import { LS_CONFIG_NAME_KEY } from "@/stores/config";

export default defineComponent({
  name: "dev-question",
  components: {
    TextFormatting,
    Replies,
  },
  setup() {
    onMounted(() => {
      if (!localStorage.getItem(LS_CONFIG_NAME_KEY)) {
        LayoutService.enableSidebar();
      }
    });

    onUnmounted(() => {
      if (!localStorage.getItem(LS_CONFIG_NAME_KEY)) {
        LayoutService.disableSidebar();
      }
    });

    return {
      getAssetPath,
    };
  },
});
</script>
