// metronic_angular_v8.2.3/angular/metronic_angular_v8.2.3_demo7/src/app/_metronic/layout/components/aside/tabs/subscriptions-tab/subscriptions-tab.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-subscriptions-tab',
  templateUrl: './subscriptions-tab.component.html',
  styleUrls: ['./subscriptions-tab.component.scss']
})
export class SubscriptionsTabComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<!--begin::Subscription-->
<div class="mx-5">
  <!--begin::Container-->
  <div class="text-center pt-10 mb-20">
    <!--begin::Title-->
    <h2 class="fs-2 fw-bolder mb-7">My Subscription</h2>
    <!--end::Title-->

    <!--begin::Description-->
    <p class="text-gray-500 fs-4 fw-bold mb-10">
      There are no customers added yet.<br />
      Kickstart your CRM by adding a your first customer
    </p>
    <!--end::Description-->

    <!--begin::Action-->
    <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#kt_modal_upgrade_plan">Upgrade Plan</a>
    <!--end::Action-->
  </div>
  <!--end::Container-->

  <!--begin::Illustration-->
  <div class="text-center px-4">
    <img src="./assets/media/illustrations/sigma-1/18.png" alt="" class="mw-100 mh-300px" />
  </div>
  <!--end::Illustration-->
</div>
<!--end::Subscription-->

// metronic_react_v8.2.3/react/metronic_react_v8.2.3_demo7/src/_metronic/layout/components/aside/Tabs/SubscriptionsTab.tsx
import {useIllustrationsPath} from '../../../../helpers'


const SubscriptionsTab = () => (
  <div className='mx-5'>
    {/*begin::Container*/}
    <div className='text-center pt-10 mb-20'>
      {/*begin::Title*/}
      <h2 className='fs-2 fw-bolder mb-7'>My Subscription</h2>
      {/*end::Title*/}

      {/*begin::Description*/}
      <p className='text-gray-500 fs-4 fw-bold mb-10'>
        There are no customers added yet.
        <br />
        Kickstart your CRM by adding a your first customer
      </p>
      {/*end::Description*/}

      {/*begin::Action*/}
      <a href='#' className='btn btn-primary'>
        Upgrade Plan
      </a>
      {/*end::Action*/}
    </div>
    {/*end::Container*/}

    {/*begin::Illustration*/}
    <div className='text-center px-4'>
      <img src={useIllustrationsPath('18.png')} alt='' className='mw-100 mh-300px' />
    </div>
    {/*end::Illustration*/}
  </div>
)

export {SubscriptionsTab}
