// metronic_angular_v8.2.3/angular/metronic_angular_v8.2.3_demo5/src/app/_metronic/layout/components/aside/aside.component.ts
import { Component, OnInit, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { NavigationCancel, NavigationEnd, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { KTHelpers } from 'src/app/_metronic/kt';
import { LayoutService } from '../../core/layout.service';
import { Tab, tabs } from './tabs';

@Component({
  selector: 'app-aside',
  templateUrl: './aside.component.html',
  styleUrls: ['./aside.component.scss'],
})
export class AsideComponent implements OnInit, OnDestroy {
  activeTab: Tab = tabs[0];
  asideMenuSecondary: boolean = true;
  private unsubscribe: Subscription[] = [];

  constructor(
    private layout: LayoutService,
    private cd: ChangeDetectorRef,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.asideMenuSecondary = this.layout.getProp(
      'aside.secondaryDisplay'
    ) as boolean;
  }

  routingChanges() {
    const routerSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd || event instanceof NavigationCancel) {
        KTHelpers.menuReinitialization();
      }
    });
    this.unsubscribe.push(routerSubscription);
  }

  setActiveTab = (
    activeTabLink:
      | 'projects'
      | 'menu'
      | 'subscription'
      | 'tasks'
      | 'notifications'
      | 'authors'
  ) => {
    const tab = tabs.find((t) => t.link === activeTabLink);
    if (tab) {
      this.activeTab = tab;
      this.cd.detectChanges();
      KTHelpers.menuReinitialization();
    }
  };

  ngOnDestroy() {
    this.unsubscribe.forEach((sb) => sb.unsubscribe());
  }
}

<!-- begin::Aside nav -->
<div class="hover-scroll-overlay-y my-5 my-lg-5 w-100 ps-4 ps-lg-0 pe-4 me-1" id="kt_aside_menu_wrapper"
  data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-height="auto"
  data-kt-scroll-dependencies="#kt_header" data-kt-scroll-wrappers="#kt_aside" data-kt-scroll-offset="5px">
  <!-- begin::Menu -->
  <div class="menu menu-column menu-active-bg menu-hover-bg menu-title-gray-700 fs-6 menu-rounded w-100"
    id="#kt_aside_menu" data-kt-menu="true">
    <!--begin::Heading-->
    <div class="menu-item">
      <div class="menu-content pb-2">
        <span class="menu-section text-muted text-uppercase fs-7 fw-bolder">Public</span>
      </div>
    </div>
    <!--end::Heading-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/main" routerLinkActive="active" class="menu-link">
        <span class="menu-title">All Questions</span>
        <span class="menu-badge">6,234</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/search" routerLinkActive="active" class="menu-link">
        <span class="menu-title">Search</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/tag" routerLinkActive="active" class="menu-link">
        <span class="menu-title">Tags</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/ask" routerLinkActive="active" class="menu-link">
        <span class="menu-title">Ask Question</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Heading-->
    <div class="menu-item pt-5">
      <div class="menu-content pb-2">
        <span class="menu-section text-muted text-uppercase fs-7 fw-bolder">My Activity</span>
      </div>
    </div>
    <!--end::Heading-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/replies" routerLinkActive="active" class="menu-link">
        <span class="menu-title">My Questions</span>
        <span class="menu-badge">24</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/main" class="menu-link">
        <span class="menu-title">Resolved</span>
        <span class="menu-badge">120</span>
      </a>
    </div>
    <!--end::Menu item-->


    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/main" class="menu-link">
        <span class="menu-title">Enrolled</span>
        <span class="menu-badge">10</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/main" class="menu-link">
        <span class="menu-title">Saved</span>
        <span class="menu-badge">6</span>
      </a>
    </div>
    <!--end::Menu item-->


    <!--begin::Heading-->
    <div class="menu-item pt-5">
      <div class="menu-content pb-2">
        <span class="menu-section text-muted text-uppercase fs-7 fw-bolder">Categories</span>
      </div>
    </div>
    <!--end::Heading-->


    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/main" class="menu-link">
        <span class="menu-title">Metronic Admin</span>
        <span class="menu-badge">1,400</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/main" class="menu-link">
        <span class="menu-title">Backend Integration</span>
        <span class="menu-badge">235</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/main" class="menu-link">
        <span class="menu-title">Suggestions</span>
        <span class="menu-badge">25</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/main" class="menu-link">
        <span class="menu-title">Pre-sale Questions</span>
        <span class="menu-badge">145</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Menu item-->
    <div class="menu-item">
      <a routerLink="/apps/tickets-system/main" class="menu-link">
        <span class="menu-title">Laravel Starter Kit</span>
        <span class="menu-badge">750</span>
      </a>
    </div>
    <!--end::Menu item-->

    <!--begin::Collapse-->
    <div class="collapse" id="kt_aside_categories_more">
      <!--begin::Menu item-->
      <div class="menu-item">
        <a routerLink="/apps/tickets-system/main" class="menu-link">
          <span class="menu-title">Blazor Integration</span>
          <span class="menu-badge">100</span>
        </a>
      </div>
      <!--end::Menu item-->

      <!--begin::Menu item-->
      <div class="menu-item">
        <a routerLink="/apps/tickets-system/main" class="menu-link">
          <span class="menu-title">Django Dashboard</span>
          <span class="menu-badge">90</span>
        </a>
      </div>
      <!--end::Menu item-->

      <!--begin::Menu item-->
      <div class="menu-item">
        <a routerLink="/apps/tickets-system/main" class="menu-link">
          <span class="menu-title">Rails CRUD</span>
          <span class="menu-badge">14</span>
        </a>
      </div>
      <!--end::Menu item-->

      <!--begin::Menu item-->
      <div class="menu-item">
        <a routerLink="/apps/tickets-system/main" class="menu-link">
          <span class="menu-title">.NET Starter Kit</span>
          <span class="menu-badge">30</span>
        </a>
      </div>
      <!--end::Menu item-->
    </div>
    <!--end::Collapse-->
  </div>
  <!-- end::Menu -->
</div>
<!-- end::Aside nav -->

// metronic_vue_v8.2.3/vue/metronic_vue_v8.2.3_demo5/src/layouts/default-layout/components/aside/Aside.vue
<template>
  <!--begin::Aside-->
  <div
    id="kt_aside"
    class="aside"
    data-kt-drawer="true"
    data-kt-drawer-name="aside"
    data-kt-drawer-activate="{default: true, lg: false}"
    data-kt-drawer-overlay="true"
    data-kt-drawer-width="{default:'200px', '300px': '225px'}"
    data-kt-drawer-direction="start"
    data-kt-drawer-toggle="#kt_aside_toggle"
  >
    <!--begin::Aside nav-->
    <div
      class="hover-scroll-overlay-y my-5 my-lg-5 w-100 ps-4 ps-lg-0 pe-4 me-1"
      id="kt_aside_menu_wrapper"
      data-kt-scroll="true"
      data-kt-scroll-activate="{default: false, lg: true}"
      data-kt-scroll-height="auto"
      data-kt-scroll-dependencies="#kt_header"
      data-kt-scroll-wrappers="#kt_aside"
      data-kt-scroll-offset="5px"
    >
      <!--begin::Menu-->
      <div
        class="menu menu-column menu-active-bg menu-hover-bg menu-title-gray-700 fs-6 menu-rounded w-100"
        id="#kt_aside_menu"
        data-kt-menu="true"
      >
        <!--begin::Heading-->
        <div class="menu-item">
          <div class="menu-content pb-2">
            <span class="menu-section text-muted text-uppercase fs-7 fw-bold"
              >Public</span
            >
          </div>
        </div>
        <!--end::Heading-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" active-class="active" class="menu-link">
            <span class="menu-title">All Questions</span>
            <span class="menu-badge">6,234</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link
            to="/apps/devs/search"
            active-class="active"
            class="menu-link"
          >
            <span class="menu-title">Search</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link
            to="/apps/devs/tag"
            active-class="active"
            class="menu-link"
          >
            <span class="menu-title">Tags</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link
            to="/apps/devs/ask"
            active-class="active"
            class="menu-link"
          >
            <span class="menu-title">Ask Question</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Heading-->
        <div class="menu-item pt-5">
          <div class="menu-content pb-2">
            <span class="menu-section text-muted text-uppercase fs-7 fw-bold"
              >My Activity</span
            >
          </div>
        </div>
        <!--end::Heading-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" class="menu-link">
            <span class="menu-title">My Questions</span>
            <span class="menu-badge">24</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" class="menu-link">
            <span class="menu-title">Resolved</span>
            <span class="menu-badge">120</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" class="menu-link">
            <span class="menu-title">Enrolled</span>
            <span class="menu-badge">10</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" class="menu-link">
            <span class="menu-title">Saved</span>
            <span class="menu-badge">6</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Heading-->
        <div class="menu-item pt-5">
          <div class="menu-content pb-2">
            <span class="menu-section text-muted text-uppercase fs-7 fw-bold"
              >Categories</span
            >
          </div>
        </div>
        <!--end::Heading-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" class="menu-link">
            <span class="menu-title">Metronic Admin</span>
            <span class="menu-badge">1,400</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" class="menu-link">
            <span class="menu-title">Backend Integration</span>
            <span class="menu-badge">235</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" class="menu-link">
            <span class="menu-title">Suggestions</span>
            <span class="menu-badge">25</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" class="menu-link">
            <span class="menu-title">Pre-sale Questions</span>
            <span class="menu-badge">145</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Menu item-->
        <div class="menu-item">
          <router-link to="/dashboard" class="menu-link">
            <span class="menu-title">Laravel Starter Kit</span>
            <span class="menu-badge">750</span>
          </router-link>
        </div>
        <!--end::Menu item-->

        <!--begin::Collapse-->
        <div class="collapse" id="kt_aside_categories_more">
          <!--begin::Menu item-->
          <div class="menu-item">
            <router-link to="/dashboard" class="menu-link">
              <span class="menu-title">Blazor Integration</span>
              <span class="menu-badge">100</span>
            </router-link>
          </div>
          <!--end::Menu item-->

          <!--begin::Menu item-->
          <div class="menu-item">
            <router-link to="/dashboard" class="menu-link">
              <span class="menu-title">Django Dashboard</span>
              <span class="menu-badge">90</span>
            </router-link>
          </div>
          <!--end::Menu item-->

          <!--begin::Menu item-->
          <div class="menu-item">
            <router-link to="/dashboard" class="menu-link">
              <span class="menu-title">Rails CRUD</span>
              <span class="menu-badge">14</span>
            </router-link>
          </div>
          <!--end::Menu item-->

          <!--begin::Menu item-->
          <div class="menu-item">
            <router-link to="/dashboard" class="menu-link">
              <span class="menu-title">.NET Starter Kit</span>
              <span class="menu-badge">30</span>
            </router-link>
          </div>
          <!--end::Menu item-->
        </div>
        <!--end::Collapse-->

        <!--begin::Heading-->
        <div class="menu-item">
          <div class="menu-link">
            <router-link
              to="/dashboard"
              class="menu-title text-muted fs-7"
              id="kt_aside_categories_toggle"
              data-bs-toggle="collapse"
              data-bs-target="#kt_aside_categories_more"
            >
              More Categories
            </router-link>
          </div>
        </div>
        <!--end::Heading-->
      </div>
      <!--end::Menu-->
    </div>
    <!--end::Aside nav-->
  </div>
  <!--end::Aside-->
</template>

<script lang="ts">
import { getAssetPath } from "@/core/helpers/assets";
import { defineComponent } from "vue";
import { useI18n } from "vue-i18n";

export default defineComponent({
  name: "KTAside",
  components: {},
  setup() {
    const { t } = useI18n();

    return {
      t,
      getAssetPath,
    };
  },
});
</script>
