// metronic_vue_v8.2.3/vue/metronic_vue_v8.2.3_demo7/src/layouts/default-layout/components/header/Header.vue
<template>
  <!--begin::Header-->
  <div
    id="kt_header"
    class="header"
    :data-kt-sticky="isHeaderSticky"
    data-kt-sticky-name="header"
    data-kt-sticky-offset="{default: '200px', lg: '300px'}"
  >
    <!--begin::Container-->
    <div
      class="d-flex align-items-center justify-content-between"
      :class="{
        'container-fluid': headerWidthFluid,
        'container-xxl': !headerWidthFluid,
      }"
      id="kt_header_container"
    >
      <PageTitle />

      <!--begin::Wrapper-->
      <div class="d-flex d-lg-none align-items-center ms-n2 me-2">
        <!--begin::Aside mobile toggle-->
        <div class="btn btn-icon btn-active-icon-primary" id="kt_aside_toggle">
          <KTIcon icon-name="abstract-14" icon-class="fs-2x" />
        </div>
        <!--end::Aside mobile toggle-->

        <!--begin::Logo-->
        <a href="#" class="d-flex align-items-center">
          <img
            alt="Logo"
            :src="getAssetPath('media/logos/demo7.svg')"
            class="h-30px"
          />
        </a>
        <!--end::Logo-->
      </div>
      <!--end::Wrapper-->

      <KTTopbar></KTTopbar>
    </div>
    <!--end::Container-->
  </div>
  <!--end::Header-->
</template>

<script lang="ts">
import { getAssetPath } from "@/core/helpers/assets";
import { computed, defineComponent } from "vue";
import KTTopbar from "@/layouts/default-layout/components/header/Topbar.vue";
import PageTitle from "@/layouts/default-layout/components/toolbar/PageTitle.vue";
import {
  headerFixed,
  headerFixedOnMobile,
  headerWidthFluid,
} from "@/layouts/default-layout/config/helper";
import KTIcon from "@/core/helpers/kt-icon/KTIcon.vue";

export default defineComponent({
  name: "KTHeader",
  components: {
    KTIcon,
    KTTopbar,
    PageTitle,
  },
  setup() {
    const isHeaderSticky = computed(() => {
      if (window.innerWidth > 768) {
        return headerFixed.value;
      } else {
        return headerFixedOnMobile.value;
      }
    });

    return {
      headerWidthFluid,
      isHeaderSticky,
      getAssetPath,
    };
  },
});
</script>

// metronic_angular_v8.2.3/angular/metronic_angular_v8.2.3_demo7/src/app/_metronic/layout/components/header/header.component.ts
import {
  Component,
  ElementRef,
  OnDestroy,
  OnInit,
  ViewChild,
} from '@angular/core';
import { NavigationCancel, NavigationEnd, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { LayoutService } from '../../core/layout.service';
import { MenuComponent } from '../../../kt/components';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit, OnDestroy {
  headerContainerCssClasses: string = '';
  @ViewChild('ktPageTitle', { static: true }) ktPageTitle: ElementRef;

  private unsubscribe: Subscription[] = [];

  constructor(private layout: LayoutService, private router: Router) {
    this.routingChanges();
  }

  ngOnInit(): void {
    this.headerContainerCssClasses =
      this.layout.getStringCSSClasses('headerContainer');
  }

  routingChanges() {
    const routerSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd || event instanceof NavigationCancel) {
        MenuComponent.reinitialization();
      }
    });
    this.unsubscribe.push(routerSubscription);
  }

  ngOnDestroy() {}
}

<div [ngClass]="headerContainerCssClasses" class="d-flex align-items-center justify-content-between"
  id="kt_header_container">
  <app-page-title #ktPageTitle
    class="page-title d-flex flex-column align-items-start justify-content-center flex-wrap mt-n5 mt-lg-0 me-lg-2 pb-2 pb-lg-0"
    data-kt-swapper="true" data-kt-swapper-mode="prepend"
    data-kt-swapper-parent="{default: '#kt_content_container', lg: '#kt_header_container'}"></app-page-title>

  <!-- begin::Wrapper -->
  <div class="d-flex d-lg-none align-items-center ms-n2 me-2">
    <!--begin::Aside mobile toggle-->
    <div class="aside-toggle btn btn-icon btn-active-icon-primary" id="kt_aside_toggle">
      <span [inlineSVG]="'./assets/media/icons/duotune/abstract/abs015.svg'" class="svg-icon svg-icon-1"></span>
    </div>
    <!--end::Aside mobile toggle-->
    <!--begin::Logo-->
    <a routerLink="/dashboard" class="d-flex align-items-center">
      <img alt="Logo" src="./assets/media/logos/demo7.svg" class="h-30px" />
    </a>
    <!--end::Logo-->
  </div>
  <!-- end::Wrapper -->
  <app-topbar class="d-flex flex-shrink-0"></app-topbar>
</div>
