// metronic_angular_v8.2.3/angular/metronic_angular_v8.2.3_demo1/src/app/_metronic/layout/components/sidebar/sidebar-menu/sidebar-menu.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-sidebar-menu',
  templateUrl: './sidebar-menu.component.html',
  styleUrls: ['./sidebar-menu.component.scss']
})
export class SidebarMenuComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<!--begin::Menu wrapper-->
<div id="kt_app_sidebar_menu_scroll" class="scroll-y my-5 mx-3" data-kt-scroll="true" data-kt-scroll-activate="true" data-kt-scroll-height="auto" data-kt-scroll-dependencies="#kt_app_sidebar_logo, #kt_app_sidebar_footer" data-kt-scroll-wrappers="#kt_app_sidebar_menu" data-kt-scroll-offset="5px" data-kt-scroll-save-state="true">
  <!--begin::Menu-->
  <div class="menu menu-column menu-rounded menu-sub-indention fw-semibold fs-6" id="#kt_app_sidebar_menu" data-kt-menu="true" data-kt-menu-expand="false">
    <!-- Dashboard -->
    <div class="menu-item">
      <a class="menu-link without-sub" routerLink="/dashboard" routerLinkActive="active">
        <span class="menu-icon">
          <app-keenicon name="element-11" class="fs-2"></app-keenicon>
        </span>
        <span class="menu-title" translate="MENU.DASHBOARD"></span>
      </a>
    </div>

    <!-- Layout builder -->
    <div class="menu-item">
      <a class="menu-link without-sub" routerLink="/builder" routerLinkActive="active">
        <span class="menu-icon">
          <app-keenicon name="switch" class="fs-2"></app-keenicon>
        </span>
        <span class="menu-title">Layout Builder</span>
      </a>
    </div>
    <!-- Separator -->
    <div class="menu-item">
      <div class="menu-content pt-8 pb-2">
        <span class="menu-section text-muted text-uppercase fs-8 ls-1">Crafted</span>
      </div>
    </div>

    <!-- Pages -->
    <div class="menu-item menu-accordion" data-kt-menu-trigger="click" routerLinkActive="here show">
      <span class="menu-link">
        <span class="menu-icon">
          <app-keenicon name="element-plus" class="fs-2"></app-keenicon>
        </span>
        <span
          class="menu-title">Pages
        </span>
        <span class="menu-arrow"></span>
      </span>
      <div class="menu-sub menu-sub-accordion" routerLinkActive="menu-active-bg">
        <div class="menu-item menu-accordion" routerLinkActive="here show" data-kt-menu-trigger="click">
          <span class="menu-link">
            <span class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title" data-link="/crafted/pages/profile">Profile
            </span>
            <span
              class="menu-arrow"></span>
          </span>
          <div class="menu-sub menu-sub-accordion" routerLinkActive="menu-active-bg">
            <div class="menu-item">
              <a class="menu-link without-sub" routerLinkActive="active"
                 routerLink="/crafted/pages/profile/overview">
                <span class="menu-bullet">
                  <span
                    class="bullet bullet-dot"></span>
                </span>
                <span class="menu-title">Overview</span>
              </a>
            </div>
            <div class="menu-item">
              <a class="menu-link without-sub" routerLinkActive="active"
                 routerLink="/crafted/pages/profile/projects">
                <span class="menu-bullet">
                  <span
                    class="bullet bullet-dot"></span>
                </span>
                <span class="menu-title">Projects</span>
              </a>
            </div>
            <div class="menu-item">
              <a class="menu-link without-sub" routerLinkActive="active"
                 routerLink="/crafted/pages/profile/campaigns">
                <span class="menu-bullet">
                  <span
                    class="bullet bullet-dot"></span>
                </span>
                <span class="menu-title">Campaigns</span>
              </a>
            </div>
            <div class="menu-item">
              <a class="menu-link without-sub" routerLinkActive="active"
                 routerLink="/crafted/pages/profile/documents">
                <span class="menu-bullet">
                  <span
                    class="bullet bullet-dot"></span>
                </span>
                <span class="menu-title">Documents</span>
              </a>
            </div>
            <div class="menu-item">
              <a class="menu-link without-sub" routerLinkActive="active"
                 routerLink="/crafted/pages/profile/connections">
                <span class="menu-bullet">
                  <span
                    class="bullet bullet-dot"></span>
                </span>
                <span class="menu-title">Connections</span>
              </a>
            </div>
          </div>
        </div>
        <div class="menu-item menu-accordion" routerLinkActive="here show" data-kt-menu-trigger="click">
          <span class="menu-link">
            <span class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title" data-link="/crafted/pages/wizards">Wizards
            </span>
            <span
              class="menu-arrow"></span>
          </span>
          <div class="menu-sub menu-sub-accordion" routerLinkActive="menu-active-bg">
            <div class="menu-item">
              <a class="menu-link without-sub" routerLinkActive="active"
                 routerLink="/crafted/pages/wizards/horizontal">
                <span class="menu-bullet">
                  <span
                    class="bullet bullet-dot"></span>
                </span>
                <span class="menu-title">Horizontal</span>
              </a>
            </div>
            <div class="menu-item">
              <a class="menu-link without-sub" routerLinkActive="active"
                 routerLink="/crafted/pages/wizards/vertical">
                <span class="menu-bullet">
                  <span
                    class="bullet bullet-dot"></span>
                </span>
                <span class="menu-title">Vertical</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Accounts -->
    <div class="menu-item menu-accordion" data-kt-menu-trigger="click" routerLinkActive="here show">
      <span class="menu-link">
        <span class="menu-icon">
          <app-keenicon name="profile-circle" class="fs-2"></app-keenicon>
        </span>
        <span class="menu-title"
              data-link="/crafted/account">Accounts
        </span>
        <span class="menu-arrow"></span>
      </span>
      <div class="menu-sub menu-sub-accordion" routerLinkActive="menu-active-bg">
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/crafted/account/overview">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title">Overview
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/crafted/account/settings">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title">Settings
            </span>
          </a>
        </div>
      </div>
    </div>

    <!-- Errors -->
    <div class="menu-item menu-accordion" data-kt-menu-trigger="click" routerLinkActive="here show">
      <span class="menu-link">
        <span class="menu-icon">
          <app-keenicon name="phone" class="fs-2"></app-keenicon>
        </span>
        <span class="menu-title"
              data-link="/error">Errors
        </span>
        <span class="menu-arrow"></span>
      </span>
      <div class="menu-sub menu-sub-accordion" routerLinkActive="menu-active-bg">
        <div class="menu-item">
          <a class="menu-link without-sub" routerLink="/error/404" routerLinkActive="active">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span class="menu-title">Error
              404
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLink="/error/500" routerLinkActive="active">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span class="menu-title">Error
              500
            </span>
          </a>
        </div>
      </div>
    </div>

    <!-- Widgets -->
    <div class="menu-item menu-accordion" data-kt-menu-trigger="click" routerLinkActive="here show">
      <span class="menu-link">
        <span class="menu-icon">
          <app-keenicon name="element-7" class="fs-2"></app-keenicon>
        </span>
        <span class="menu-title"
              data-link="/crafted/widgets">Widgets
        </span>
        <span class="menu-arrow"></span>
      </span>
      <div class="menu-sub menu-sub-accordion" routerLinkActive="menu-active-bg">
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/crafted/widgets/lists">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title">Lists
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/crafted/widgets/statistics">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title">Statistics
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/crafted/widgets/charts">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title">Charts
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/crafted/widgets/mixed">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title">Mixed
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/crafted/widgets/tables">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title">Tables
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/crafted/widgets/feeds">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span
              class="menu-title">Feeds
            </span>
          </a>
        </div>
      </div>
    </div>

    <!-- Separator -->
    <div class="menu-item">
      <div class="menu-content pt-8 pb-2">
        <span class="menu-section text-muted text-uppercase fs-8 ls-1">Apps</span>
      </div>
    </div>

    <!-- Chat -->
    <div class="menu-item menu-accordion" data-kt-menu-trigger="click" routerLinkActive="here show">
      <span class="menu-link">
        <span class="menu-icon">
          <app-keenicon name="message-text-2" class="fs-2"></app-keenicon>
        </span>
        <span class="menu-title"
              data-link="/apps/chat">Chat
        </span>
        <span class="menu-arrow"></span>
      </span>
      <div class="menu-sub menu-sub-accordion" routerLinkActive="menu-active-bg">
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/apps/chat/private-chat">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span class="menu-title">Private Chat
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/apps/chat/group-chat">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span class="menu-title">Group Chat
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/apps/chat/drawer-chat">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span class="menu-title">Drawer Chat
            </span>
          </a>
        </div>
      </div>
    </div>

    <!-- Customers -->
    <div class="menu-item menu-accordion" data-kt-menu-trigger="click" routerLinkActive="here show">
      <span class="menu-link">
        <span class="menu-icon">
          <app-keenicon name="profile-user" class="fs-2"></app-keenicon>
        </span>
        <span class="menu-title" data-link="/apps">User Management
        </span>
        <span class="menu-arrow"></span>
      </span>
      <div class="menu-sub menu-sub-accordion" routerLinkActive="menu-active-bg">
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/apps/users">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span class="menu-title">Users
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/apps/roles">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span class="menu-title">Roles
            </span>
          </a>
        </div>
        <div class="menu-item">
          <a class="menu-link without-sub" routerLinkActive="active" routerLink="/apps/permissions">
            <span
              class="menu-bullet">
              <span class="bullet bullet-dot"></span>
            </span>
            <span class="menu-title">Permissions
            </span>
          </a>
        </div>
      </div>
    </div>
  </div>
  <!--end::Menu-->
</div>
<!--end::Menu wrapper-->

// metronic_vue_v8.2.3/vue/metronic_vue_v8.2.3_demo1/src/layouts/default-layout/components/sidebar/SidebarMenu.vue
<template>
  <!--begin::sidebar menu-->
  <div class="app-sidebar-menu overflow-hidden flex-column-fluid">
    <!--begin::Menu wrapper-->
    <div
      id="kt_app_sidebar_menu_wrapper"
      class="app-sidebar-wrapper hover-scroll-overlay-y my-5"
      data-kt-scroll="true"
      data-kt-scroll-activate="true"
      data-kt-scroll-height="auto"
      data-kt-scroll-dependencies="#kt_app_sidebar_logo, #kt_app_sidebar_footer"
      data-kt-scroll-wrappers="#kt_app_sidebar_menu"
      data-kt-scroll-offset="5px"
      data-kt-scroll-save-state="true"
    >
      <!--begin::Menu-->
      <div
        id="#kt_app_sidebar_menu"
        class="menu menu-column menu-rounded menu-sub-indention px-3"
        data-kt-menu="true"
      >
        <template v-for="(item, i) in MainMenuConfig" :key="i">
          <div v-if="item.heading" class="menu-item pt-5">
            <div class="menu-content">
              <span class="menu-heading fw-bold text-uppercase fs-7">
                {{ translate(item.heading) }}
              </span>
            </div>
          </div>
          <template v-for="(menuItem, j) in item.pages" :key="j">
            <template v-if="menuItem.heading">
              <div class="menu-item">
                <router-link
                  v-if="menuItem.route"
                  class="menu-link"
                  active-class="active"
                  :to="menuItem.route"
                >
                  <span
                    v-if="menuItem.keenthemesIcon || menuItem.bootstrapIcon"
                    class="menu-icon"
                  >
                    <i
                      v-if="sidebarMenuIcons === 'bootstrap'"
                      :class="menuItem.bootstrapIcon"
                      class="bi fs-3"
                    ></i>
                    <KTIcon
                      v-else-if="sidebarMenuIcons === 'keenthemes'"
                      :icon-name="menuItem.keenthemesIcon"
                      icon-class="fs-2"
                    />
                  </span>
                  <span class="menu-title">{{
                    translate(menuItem.heading)
                  }}</span>
                </router-link>
              </div>
            </template>
            <div
              v-if="menuItem.sectionTitle && menuItem.route"
              :class="{ show: hasActiveChildren(menuItem.route) }"
              class="menu-item menu-accordion"
              data-kt-menu-sub="accordion"
              data-kt-menu-trigger="click"
            >
              <span class="menu-link">
                <span
                  v-if="menuItem.keenthemesIcon || menuItem.bootstrapIcon"
                  class="menu-icon"
                >
                  <i
                    v-if="sidebarMenuIcons === 'bootstrap'"
                    :class="menuItem.bootstrapIcon"
                    class="bi fs-3"
                  ></i>
                  <KTIcon
                    v-else-if="sidebarMenuIcons === 'keenthemes'"
                    :icon-name="menuItem.keenthemesIcon"
                    icon-class="fs-2"
                  />
                </span>
                <span class="menu-title">{{
                  translate(menuItem.sectionTitle)
                }}</span>
                <span class="menu-arrow"></span>
              </span>
              <div
                :class="{ show: hasActiveChildren(menuItem.route) }"
                class="menu-sub menu-sub-accordion"
              >
                <template v-for="(item2, k) in menuItem.sub" :key="k">
                  <div v-if="item2.heading" class="menu-item">
                    <router-link
                      v-if="item2.route"
                      class="menu-link"
                      active-class="active"
                      :to="item2.route"
                    >
                      <span class="menu-bullet">
                        <span class="bullet bullet-dot"></span>
                      </span>
                      <span class="menu-title">{{
                        translate(item2.heading)
                      }}</span>
                    </router-link>
                  </div>
                  <div
                    v-if="item2.sectionTitle && item2.route"
                    :class="{ show: hasActiveChildren(item2.route) }"
                    class="menu-item menu-accordion"
                    data-kt-menu-sub="accordion"
                    data-kt-menu-trigger="click"
                  >
                    <span class="menu-link">
                      <span class="menu-bullet">
                        <span class="bullet bullet-dot"></span>
                      </span>
                      <span class="menu-title">{{
                        translate(item2.sectionTitle)
                      }}</span>
                      <span class="menu-arrow"></span>
                    </span>
                    <div
                      :class="{ show: hasActiveChildren(item2.route) }"
                      class="menu-sub menu-sub-accordion"
                    >
                      <template v-for="(item3, k) in item2.sub" :key="k">
                        <div v-if="item3.heading" class="menu-item">
                          <router-link
                            v-if="item3.route"
                            class="menu-link"
                            active-class="active"
                            :to="item3.route"
                          >
                            <span class="menu-bullet">
                              <span class="bullet bullet-dot"></span>
                            </span>
                            <span class="menu-title">{{
                              translate(item3.heading)
                            }}</span>
                          </router-link>
                        </div>
                      </template>
                    </div>
                  </div>
                </template>
              </div>
            </div>
          </template>
        </template>

        <div class="menu-item pt-5">
          <!--begin:Menu content-->
          <div class="menu-content">
            <span class="menu-heading fw-bold text-uppercase fs-7">Help</span>
          </div>
          <!--end:Menu content-->
        </div>
        <!--begin:Menu item-->
        <div class="menu-item">
          <!--begin:Menu link-->
          <a
            class="menu-link"
            href="https://preview.keenthemes.com/metronic8/vue/docs/base/utilities"
          >
            <span class="menu-icon">
              <i
                v-if="sidebarMenuIcons === 'bootstrap'"
                class="bi bi-briefcase fs-3"
              ></i>
              <KTIcon
                v-else-if="sidebarMenuIcons === 'keenthemes'"
                icon-name="rocket"
                icon-class="fs-2"
              />
            </span>
            <span class="menu-title">Components</span>
          </a>
          <!--end:Menu link-->
        </div>
        <!--end:Menu item-->
        <div class="menu-item">
          <!--begin:Menu link-->
          <a
            class="menu-link"
            href="https://preview.keenthemes.com/metronic8/vue/docs/index"
          >
            <span class="menu-icon">
              <i
                v-if="sidebarMenuIcons === 'bootstrap'"
                class="bi bi-box fs-3"
              ></i>
              <KTIcon
                v-else-if="sidebarMenuIcons === 'keenthemes'"
                icon-name="abstract-26"
                icon-class="fs-2"
              />
            </span>
            <span class="menu-title">Documentation</span>
          </a>
          <!--end:Menu link-->
        </div>
        <!--begin:Menu item-->
        <!--end:Menu item-->
        <div class="menu-item">
          <!--begin:Menu link-->
          <a
            class="menu-link"
            href="https://preview.keenthemes.com/metronic8/vue/docs/getting-started/changelog"
          >
            <span class="menu-icon">
              <i
                v-if="sidebarMenuIcons === 'bootstrap'"
                class="bi bi-diagram-3 fs-3"
              ></i>
              <KTIcon
                v-else-if="sidebarMenuIcons === 'keenthemes'"
                icon-name="code"
                icon-class="fs-2"
              />
            </span>
            <span class="menu-title">Changelog</span>
          </a>
          <!--end:Menu link-->
        </div>
        <!--begin:Menu item-->
        <!--end:Menu item-->
      </div>
      <!--end::Menu-->
    </div>
    <!--end::Menu wrapper-->
  </div>
  <!--end::sidebar menu-->
</template>

<script lang="ts">
import { getAssetPath } from "@/core/helpers/assets";
import { defineComponent, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import MainMenuConfig from "@/layouts/default-layout/config/MainMenuConfig";
import { sidebarMenuIcons } from "@/layouts/default-layout/config/helper";
import { useI18n } from "vue-i18n";

export default defineComponent({
  name: "sidebar-menu",
  components: {},
  setup() {
    const { t, te } = useI18n();
    const route = useRoute();
    const scrollElRef = ref<null | HTMLElement>(null);

    onMounted(() => {
      if (scrollElRef.value) {
        scrollElRef.value.scrollTop = 0;
      }
    });

    const translate = (text: string) => {
      if (te(text)) {
        return t(text);
      } else {
        return text;
      }
    };

    const hasActiveChildren = (match: string) => {
      return route.path.indexOf(match) !== -1;
    };

    return {
      hasActiveChildren,
      MainMenuConfig,
      sidebarMenuIcons,
      translate,
      getAssetPath,
    };
  },
});
</script>
