// metronic_react_v8.2.3/react/metronic_react_v8.2.3_demo7/src/_metronic/layout/components/aside/Tabs/NotificationsTab.tsx
import {Link} from 'react-router-dom'
import {KTIcon} from '../../../../helpers'

const notifications: ReadonlyArray<{
  color: string
  icon: string
  title: string
  text: string
  number: string
}> = [
  {
    color: 'warning',
    icon: 'abstract-26',
    title: 'Group lunch celebration',
    text: 'Due in 29 Days',
    number: '+28%',
  },

  {
    color: 'success',
    icon: 'file-added',
    title: 'Navigation optimization',
    text: 'Due in 2 Days',
    number: '+50%',
  },

  {
    color: 'danger',
    icon: 'message-text-2',
    title: 'Humbert Bresnen',
    text: 'Due in 5 Days',
    number: '-27%',
  },

  {
    color: 'info',
    icon: 'chart',
    title: 'Air B & B - Real Estate',
    text: 'Due in 8 Days',
    number: '+21%',
  },

  {
    color: 'primary',
    icon: 'arrows-loop',
    title: 'B & Q - Food Company',
    text: 'Due in 6 Days',
    number: '+12%',
  },

  {
    color: 'danger',
    icon: 'pencil',
    title: 'Nexa - Next generation',
    text: 'Due in 4 Days',
    number: '+34%',
  },
]

const NotificationsTab = () => (
  <div className='mx-5'>
    {/*begin::Header*/}
    <h3 className='fw-bolder text-gray-900 mb-10 mx-0'>Notifications</h3>
    {/*end::Header*/}

    {/*begin::Body*/}
    <div className='mb-12'>
      {notifications.map((n) => (
        <div
          key={n.text}
          className={`d-flex align-items-center bg-light-${n.color} rounded p-5 mb-7`}
        >
          <KTIcon iconName={n.icon} className={`-${n.color} me-5 fs-1 text-${n.color}`} />

          {/*begin::Title*/}
          <div className='flex-grow-1 me-2'>
            <Link
              to='/crafted/widgets/lists'
              className='fw-bolder text-gray-800 text-hover-primary fs-6'
            >
              {n.title}
            </Link>

            <span className='text-muted fw-bold d-block'>{n.text}</span>
          </div>
          {/*end::Title*/}

          {/*begin::Lable*/}
          <span className={`fw-bolder text-${n.color} py-1`}>{n.number}</span>
          {/*end::Lable*/}
        </div>
      ))}
    </div>
    {/*end::Body*/}
  </div>
)

export {NotificationsTab}

// metronic_angular_v8.2.3/angular/metronic_angular_v8.2.3_demo5/src/app/_metronic/layout/components/aside/tabs/notifications-tab/notifications-tab.component.ts
import { Component, OnInit } from '@angular/core';

type Notification = {
  color: 'warning' | 'success' | 'danger' | 'info' | 'primary' | 'danger';
  icon: string;
  title: string;
  text: string;
  number: string;
};

const notifications: ReadonlyArray<Notification> = [
  {
    color: 'warning',
    icon: './assets/media/icons/duotune/abstract/abs027.svg',
    title: 'Group lunch celebration',
    text: 'Due in 29 Days',
    number: '+28%',
  },

  {
    color: 'success',
    icon: './assets/media/icons/duotune/files/fil008.svg',
    title: 'Navigation optimization',
    text: 'Due in 2 Days',
    number: '+50%',
  },

  {
    color: 'danger',
    icon: './assets/media/icons/duotune/communication/com012.svg',
    title: 'Humbert Bresnen',
    text: 'Due in 5 Days',
    number: '-27%',
  },

  {
    color: 'info',
    icon: './assets/media/icons/duotune/finance/fin006.svg',
    title: 'Air B & B - Real Estate',
    text: 'Due in 8 Days',
    number: '+21%',
  },

  {
    color: 'primary',
    icon: './assets/media/icons/duotune/arrows/arr031.svg',
    title: 'B & Q - Food Company',
    text: 'Due in 6 Days',
    number: '+12%',
  },

  {
    color: 'danger',
    icon: './assets/media/icons/duotune/art/art005.svg',
    title: 'Nexa - Next generation',
    text: 'Due in 4 Days',
    number: '+34%',
  },
];
@Component({
  selector: 'app-notifications-tab',
  templateUrl: './notifications-tab.component.html',
  styleUrls: ['./notifications-tab.component.scss'],
})
export class NotificationsTabComponent implements OnInit {
  allNotifications: ReadonlyArray<Notification> = [];
  constructor() {}

  ngOnInit(): void {
    this.allNotifications = notifications;
  }
}

<div class="mx-5">
  <!--begin::Header-->
  <h3 class="fw-bolder text-gray-900 mb-10 mx-0">Notifications</h3>
  <!--end::Header-->

  <!--begin::Body-->
  <div class="mb-12">

    <!--begin::Item-->
    <div *ngFor="let item of allNotifications"
      class="d-flex align-items-center bg-light-{{item.color}} rounded p-5 mb-7">
      <!--begin::Icon-->
      <span class="svg-icon svg-icon-{{item.color}} me-5">
        <span [inlineSVG]="item.icon" class="svg-icon-1 svg-icon-{{item.color}}"></span>
      </span>
      <!--end::Icon-->

      <!--begin::Title-->
      <div class="flex-grow-1 me-2">
        <a class="fw-bolder text-gray-800 text-hover-primary fs-6">{{item.title}}</a>
        <span class="text-muted fw-bold d-block">{{item.text}}></span>
      </div>
      <!--end::Title-->

      <!--begin::Lable-->
      <span class="fw-bolder text-{{item.color}} py-1">{{item.number}}</span>
      <!--end::Lable-->
    </div>
    <!--end::Item-->
  </div>
  <!--end::Body-->
</div>
