// metronic_react_v8.2.3/react/custom_app/src/_metronic/partials/widgets/_new/lists/ListsWidget26.tsx

import {Fragment} from 'react'
import {KTIcon} from '../../../../helpers'

type Props = {
  className: string
}

const rows: Array<{description: string}> = [
  {description: 'Avg. Client Rating'},
  {description: 'Instagram Followers'},
  {description: 'Google Ads CPC'},
]

const ListsWidget26 = ({className}: Props) => (
  <div className={`card card-flush ${className}`}>
    <div className='card-header pt-5'>
      <h3 className='card-title text-gray-800 fw-bold'>External Links</h3>
      <div className='card-toolbar'></div>
    </div>
    <div className='card-body pt-5'>
      {rows.map((row, index) => (
        <Fragment key={`lw26-rows-${index}`}>
          <div className='d-flex flex-stack'>
            <a href='#' className='text-primary fw-semibold fs-6 me-2'>
              {row.description}
            </a>
            <button
              type='button'
              className='btn btn-icon btn-sm h-auto btn-color-gray-500 btn-active-color-primary justify-content-end'
            >
              <KTIcon iconName='exit-right-corner' className='fs-2' />
            </button>
          </div>
          {rows.length - 1 > index && <div className='separator separator-dashed my-3' />}
        </Fragment>
      ))}
    </div>
  </div>
)
export {ListsWidget26}

// metronic_angular_v8.2.3/angular/metronic_angular_v8.2.3_demo1/src/app/_metronic/partials/content/widgets/_new/lists/lists-widget26/lists-widget26.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-lists-widget26',
  templateUrl: './lists-widget26.component.html',
  styleUrls: ['./lists-widget26.component.scss'],
})
export class ListsWidget26Component implements OnInit {
  rows: Array<{ description: string }>;

  constructor() {}

  ngOnInit(): void {
    this.rows = [
      { description: 'Avg. Client Rating' },
      { description: 'Instagram Followers' },
      { description: 'Google Ads CPC' },
    ];
  }
}

<div class="card card-flush h-lg-50">
  <!--begin::Header-->
  <div class="card-header pt-5">
    <!--begin::Title-->
    <h3 class="card-title text-gray-800 fw-bold">External Links</h3>
    <!--end::Title-->

    <!--begin::Toolbar-->
    <div class="card-toolbar">
      <!--begin::Menu-->
      <button class="btn btn-icon btn-color-gray-500 btn-active-color-primary justify-content-end"
        data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-overflow="true">
        <app-keenicon name="dots-square" class="fs-1 text-gray300 me-n1"></app-keenicon>
      </button>
      <app-dropdown-menu2></app-dropdown-menu2>
      <!--end::Menu-->
    </div>
    <!--end::Toolbar-->
  </div>
  <!--end::Header-->

  <!--begin::Body-->
  <div class="card-body pt-5">
    <ng-container *ngFor="let row of rows; let i = index">
      <!--begin::Item-->
      <div class="d-flex flex-stack">
        <!--begin::Section-->
        <a href="#" class="text-primary fw-semibold fs-6 me-2">{{row.description}}</a>
        <!--end::Section-->
        <!--begin::Action-->
        <button type="button" class="btn btn-icon btn-sm h-auto btn-color-gray-500 btn-active-color-primary justify-content-end">
          <app-keenicon name="exit-right-corner" class="fs-2"></app-keenicon>
        </button>
        <!--end::Action-->
      </div>
      <!--end::Item-->

      <ng-container *ngIf="i < (rows.length - 1)">
        <!--begin::Separator-->
        <div class="separator separator-dashed my-3"></div>
        <!--end::Separator-->
      </ng-container>
    </ng-container>
  </div>
  <!--end::Body-->
</div>
