// metronic_vue_v8.2.3/vue/metronic_vue_v8.2.3_demo5/src/layouts/default-layout/components/header/Header.vue
<template>
  <!--begin::Header-->
  <div id="kt_header" class="header align-items-stretch">
    <!--begin::Container-->
    <div
      class="d-flex align-items-stretch justify-content-between"
      :class="{
        'container-fluid': headerWidthFluid,
        'container-xxl': !headerWidthFluid,
      }"
    >
      <!--begin::Brand-->
      <div
        class="d-flex align-items-center flex-grow-1 flex-lg-grow-0 w-lg-225px me-5"
      >
        <!--begin::Aside mobile toggle-->
        <div
          class="btn btn-icon btn-active-icon-primary ms-n2 me-2 d-flex d-lg-none"
          id="kt_aside_toggle"
        >
          <KTIcon icon-name="abstract-14" icon-class="fs-1" />
        </div>
        <!--end::Aside mobile toggle-->

        <!--begin::Logo-->
        <a href="#">
          <img
            alt="Logo"
            :src="getAssetPath('media/logos/demo5.svg')"
            class="d-none d-lg-inline h-30px"
          />
          <img
            alt="Logo"
            :src="getAssetPath('media/logos/demo5-mobile.svg')"
            class="d-lg-none h-25px"
          />
        </a>
        <!--end::Logo-->
      </div>
      <!--end::Brand-->

      <!--begin::Wrapper-->
      <div
        class="d-flex align-items-stretch justify-content-between flex-lg-grow-1"
      >
        <!--begin::Navbar-->
        <div class="d-flex align-items-stretch" id="kt_header_nav">
          <KTMenu />
        </div>
        <!--end::Navbar-->

        <KTTopbar />
      </div>
      <!--end::Wrapper-->
    </div>
    <!--end::Container-->
  </div>
  <!--end::Header-->
</template>

<script lang="ts">
import { getAssetPath } from "@/core/helpers/assets";
import { defineComponent } from "vue";
import KTTopbar from "@/layouts/default-layout/components/header/Topbar.vue";
import KTMenu from "@/layouts/default-layout/components/header/Menu.vue";

import {
  asideDisplay,
  headerLeft,
  headerWidthFluid,
} from "@/layouts/default-layout/config/helper";

export default defineComponent({
  name: "KTHeader",
  components: {
    KTTopbar,
    KTMenu,
  },
  setup() {
    return {
      headerWidthFluid,
      headerLeft,
      asideDisplay,
      getAssetPath,
    };
  },
});
</script>

// metronic_angular_v8.2.3/angular/metronic_angular_v8.2.3_demo5/src/app/_metronic/layout/components/header/header.component.ts
import {
  Component,
  ElementRef,
  OnDestroy,
  OnInit,
  ViewChild,
} from "@angular/core";
import { NavigationCancel, NavigationEnd, Router } from "@angular/router";
import { Subscription } from "rxjs";
import { LayoutService } from "../../core/layout.service";
import { MenuComponent } from "../../../kt/components";

@Component({
  selector: "app-header",
  templateUrl: "./header.component.html",
})
export class HeaderComponent implements OnInit, OnDestroy {
  headerContainerCssClasses: string = "";
  showHeaderMenu: boolean = false;
  @ViewChild("ktPageTitle", { static: true }) ktPageTitle: ElementRef;

  private unsubscribe: Subscription[] = [];

  constructor(private layout: LayoutService, private router: Router) {
    this.routingChanges();
    const headerMenu = this.layout.getProp("header.menu") as
      | boolean
      | undefined;
    if (headerMenu) {
      this.showHeaderMenu = true;
    }
  }

  ngOnInit(): void {
    this.headerContainerCssClasses =
      this.layout.getStringCSSClasses("headerContainer");
  }

  routingChanges() {
    const routerSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd || event instanceof NavigationCancel) {
        MenuComponent.reinitialization();
      }
    });
    this.unsubscribe.push(routerSubscription);
  }

  ngOnDestroy() {}
}

<!--begin::Container-->

<div [ngClass]="headerContainerCssClasses" class="d-flex align-items-stretch justify-content-between"
  id="kt_header_container">

  <!--begin::Brand-->
  <div class="d-flex align-items-center flex-grow-1 flex-lg-grow-0 w-lg-225px me-5">
    <!--begin::Aside mobile toggle-->
    <div class="btn btn-icon btn-active-icon-primary ms-n2 me-2 d-flex d-lg-none" id="kt_aside_toggle">
      <span [inlineSVG]="'./assets/media/icons/duotune/abstract/abs015.svg'" class="svg-icon svg-icon-1"></span>
    </div>
    <!--end::Aside mobile toggle-->

    <!--begin::Logo-->
    <a routerLink="/apps/tickets-system/main">
      <img alt="Logo" src="./assets/media/logos/demo5.svg" class="d-none d-lg-inline h-30px" />
      <img alt="Logo" src="./assets/media/logos/demo5-mobile.svg" class="d-lg-none h-25px" />
    </a>
    <!--end::Logo-->
  </div>
  <!--end::Brand-->

  <!-- begin::Wrapper -->
  <div class="d-flex align-items-stretch justify-content-between flex-lg-grow-1">
    <!--begin::Navbar-->
    <div class="d-flex align-items-stretch" id="kt_header_nav">
      <ng-container *ngIf="showHeaderMenu">
        <app-header-menu class="header-menu align-items-stretch" data-kt-drawer="true" data-kt-drawer-name="header-menu"
          data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true"
          data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="end"
          data-kt-drawer-toggle="#kt_header_menu_mobile_toggle" data-kt-swapper="true" data-kt-swapper-mode="prepend"
          data-kt-swapper-parent="{default: '#kt_body', lg: '#kt_header_nav'}"></app-header-menu>
      </ng-container>
    </div>
    <!--end::Navbar-->

    <app-topbar class="d-flex align-items-stretch flex-shrink-0"></app-topbar>
  </div>
  <!-- end::Wrapper -->
</div>
<!--end::Container-->
