// metronic_angular_v8.2.3/angular/metronic_angular_v8.2.3_demo5/src/app/_metronic/layout/components/topbar/topbar.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-topbar",
  templateUrl: "./topbar.component.html",
})
export class TopbarComponent {
  itemClass: string = "ms-1 ms-lg-2";
  btnClass: string =
    "btn btn-icon btn-active-light btn-active-color-primary w-30px h-30px w-md-40px h-md-40px";
  toolbarButtonIconSizeClass: string = "svg-icon-1";
}

<!--begin::Search-->
<div class="d-flex align-items-stretch" [ngClass]="itemClass">
  <div id="kt_header_search" class="header-search d-flex align-items-stretch" data-kt-menu-trigger="click"
    data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end" data-kt-menu-flip="bottom">
    <!-- begin::Search toggle -->
    <div class="d-flex align-items-center" data-kt-search-element="toggle" id="kt_header_search_toggle">
      <div class="btn btn-icon btn-active-light btn-active-color-primary w-30px h-30px w-md-40px h-md-40px">
        <span [inlineSVG]="'./assets/media/icons/duotune/general/gen021.svg'" class="svg-icon"
          [ngClass]="toolbarButtonIconSizeClass"></span>
      </div>
    </div>
    <!-- end::Search toggle -->

  </div>
  <!-- begin::Menu -->
  <app-search-result-inner class="menu menu-sub menu-sub-dropdown p-7 w-325px w-md-375px"
    data-kt-search-element="content" class="menu menu-sub menu-sub-dropdown p-7 w-325px w-md-375px" data-kt-menu="true">
  </app-search-result-inner>
  <!-- end::Menu -->
</div>
<!--end::Search-->

<!--begin::Activities-->
<div class="d-flex align-items-center" [ngClass]="itemClass">
  <!--begin::Drawer toggle-->
  <div [ngClass]="btnClass" id="kt_activities_toggle">
    <span [inlineSVG]="'./assets/media/icons/duotune/general/gen032.svg'" class="svg-icon"
      [ngClass]="toolbarButtonIconSizeClass"></span>
  </div>
  <!--end::Drawer toggle-->
</div>
<!--end::Activities-->

<!--begin::Chat-->
<div class="d-flex align-items-center" [ngClass]="itemClass">
  <!--begin::Menu wrapper-->
  <div [ngClass]="btnClass" class="position-relative" id="kt_drawer_chat_toggle">
    <span [inlineSVG]="'./assets/media/icons/duotune/communication/com012.svg'" class="svg-icon"
      [ngClass]="toolbarButtonIconSizeClass"></span>
    <span
      class="bullet bullet-dot bg-success h-6px w-6px position-absolute translate-middle top-0 start-50 animation-blink">
    </span>
  </div>
  <!--end::Menu wrapper-->
</div>
<!--end::Chat-->

<!--begin::Notifications-->
<div class="d-flex align-items-center" [ngClass]="itemClass">
  <!--begin::Menu- wrapper-->
  <div [ngClass]="btnClass" class="position-relative" data-kt-menu-trigger="click" data-kt-menu-attach="parent"
    data-kt-menu-placement="bottom-end">
    <span [inlineSVG]="'./assets/media/icons/duotune/abstract/abs038.svg'" class="svg-icon"
      [ngClass]="toolbarButtonIconSizeClass"></span>
  </div>
  <app-notifications-inner></app-notifications-inner>
  <!--end::Menu wrapper-->
</div>
<!--end::Notifications-->

<!-- begin::Theme mode -->
<app-theme-mode-switcher class="d-flex align-items-center" [ngClass]="itemClass"
  toggleBtnClass="{`btn-active-light-primary btn-custom ${btnClass}`}">
</app-theme-mode-switcher>
<!-- end::Theme mode -->

<!--begin::User-->
<div class="d-flex align-items-center ms-lg-5" id="kt_header_user_menu_toggle">
  <!--begin::User info-->
  <div class="btn btn-active-light d-flex align-items-center bg-hover-light py-2 px-2 px-md-3"
    data-kt-menu-trigger="click" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end">

    <!--begin::Name-->
    <div class="d-none d-md-flex flex-column align-items-end justify-content-center me-2">
      <span class="text-muted fs-7 fw-bold lh-1 mb-2">Hello</span>
      <span class="text-gray-900 fs-base fw-bolder lh-1">Richard</span>
    </div>
    <!--end::Name-->

    <!--begin::Symbol-->
    <div class="symbol symbol-30px symbol-md-40px">
      <img src="./assets/media/avatars/300-1.jpg" alt="image" />
    </div>
    <!--end::Symbol-->
  </div>
  <!--end::User info-->

  <app-user-inner></app-user-inner>
</div>
<!--end::User -->

// metronic_react_v8.2.3/react/metronic_react_v8.2.3_demo5/src/_metronic/layout/components/header/Topbar.tsx
import clsx from 'clsx'
import React, {FC} from 'react'
import {KTIcon, toAbsoluteUrl} from '../../../helpers'
import {
  HeaderNotificationsMenu,
  HeaderUserMenu,
  QuickLinks,
  Search,
  ThemeModeSwitcher,
} from '../../../partials'

const toolbarButtonMarginClass = 'ms-1 ms-lg-3',
  toolbarButtonHeightClass = 'w-30px h-30px w-md-40px h-md-40px',
  toolbarButtonIconSizeClass = 'fs-1'

const Topbar: FC = () => {
  return (
    <div className='d-flex align-items-stretch flex-shrink-0'>
      <div className='topbar d-flex align-items-stretch flex-shrink-0'>
        {/* Search */}
        <div className={clsx('d-flex align-items-stretch', toolbarButtonMarginClass)}>
          <Search />
        </div>
        {/* Activities */}
        <div className={clsx('d-flex align-items-center ', toolbarButtonMarginClass)}>
          {/* begin::Drawer toggle */}
          <div
            className={clsx(
              'btn btn-icon btn-active-light-primary btn-custom',
              toolbarButtonHeightClass
            )}
            id='kt_activities_toggle'
          >
            <KTIcon iconName='chart-simple' className={toolbarButtonIconSizeClass} />
          </div>
          {/* end::Drawer toggle */}
        </div>

        {/* CHAT */}
        <div className={clsx('d-flex align-items-center', toolbarButtonMarginClass)}>
          {/* begin::Menu wrapper */}
          <div
            className={clsx(
              'btn btn-icon btn-active-light-primary btn-custom position-relative',
              toolbarButtonHeightClass
            )}
            id='kt_drawer_chat_toggle'
          >
            <KTIcon iconName='message-text-2' className={toolbarButtonIconSizeClass} />

            <span className='bullet bullet-dot bg-success h-6px w-6px position-absolute translate-middle top-0 start-50 animation-blink'></span>
          </div>
          {/* end::Menu wrapper */}
        </div>

        {/* NOTIFICATIONS */}
        <div className={clsx('d-flex align-items-center', toolbarButtonMarginClass)}>
          {/* begin::Menu- wrapper */}
          <div
            className={clsx(
              'btn btn-icon btn-active-light-primary btn-custom',
              toolbarButtonHeightClass
            )}
            data-kt-menu-trigger='click'
            data-kt-menu-attach='parent'
            data-kt-menu-placement='bottom-end'
            data-kt-menu-flip='bottom'
          >
            <KTIcon iconName='abstract-36' className={toolbarButtonIconSizeClass} />
          </div>
          <HeaderNotificationsMenu />
          {/* end::Menu wrapper */}
        </div>

        {/* Quick links */}
        <div className={clsx('d-flex align-items-center', toolbarButtonMarginClass)}>
          {/* begin::Menu wrapper */}
          <div
            className={clsx(
              'btn btn-icon btn-active-light-primary btn-custom',
              toolbarButtonHeightClass
            )}
            data-kt-menu-trigger='click'
            data-kt-menu-attach='parent'
            data-kt-menu-placement='bottom-end'
            data-kt-menu-flip='bottom'
          >
            <KTIcon iconName='element-11' className={toolbarButtonIconSizeClass} />
          </div>
          <QuickLinks />
          {/* end::Menu wrapper */}
        </div>

        {/* begin::Theme mode */}
        <div className={'d-flex align-items-center ms-lg-5'}>
          <ThemeModeSwitcher toggleBtnClass='btn btn-active-light d-flex align-items-center bg-hover-light py-2 px-2 px-md-3' />
        </div>
        {/* end::Theme mode */}

        {/* begin::User */}
        <div className='d-flex align-items-center ms-lg-5' id='kt_header_user_menu_toggle'>
          <div
            className='btn btn-active-light d-flex align-items-center bg-hover-light py-2 px-2 px-md-3'
            data-kt-menu-trigger='click'
            data-kt-menu-attach='parent'
            data-kt-menu-placement='bottom-end'
          >
            <div className='d-none d-md-flex flex-column align-items-end justify-content-center me-2'>
              <span className='text-muted fs-7 fw-bold lh-1 mb-2'>Hello</span>
              <span className='text-gray-900 fs-base fw-bolder lh-1'>Richard</span>
            </div>

            <div className='symbol symbol-30px symbol-md-40px'>
              <img src={toAbsoluteUrl('media/avatars/300-1.jpg')} alt='avatar' />
            </div>
          </div>
          <HeaderUserMenu />
        </div>
        {/* end::User */}

        {/* Header menu toggle */}
        <div className='d-flex d-lg-none align-items-center me-n2' title='Show header menu'>
          <button
            className='btn btn-icon btn-active-light-primary w-30px h-30px w-md-40px h-md-40px'
            id='kt_header_menu_mobile_toggle'
          >
            <KTIcon iconName='text-align-left' className='fs-1' />
          </button>
        </div>
      </div>
    </div>
  )
}

export {Topbar}
