// metronic_angular_v8.2.3/angular/metronic_angular_v8.2.3_demo1/src/app/_metronic/partials/content/widgets/_new/cards/cards-widget7/cards-widget7.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-cards-widget7',
  templateUrl: './cards-widget7.component.html',
  styleUrls: ['./cards-widget7.component.scss'],
})
export class CardsWidget7Component implements OnInit {
  @Input() cssClass: string = '';
  @Input() icon: boolean = false;
  @Input() stats: number = 357;
  @Input() description: string = 'Professionals';
  @Input() labelColor: string = 'dark';
  @Input() textColor: string = 'gray-300';
  items: Array<{ name: string; initials?: string; state?: string, src?: string }>;

  constructor() {}

  ngOnInit(): void {
    this.items = [
      { name: 'Alan Warden', initials: 'A', state: 'warning' },
      { name: 'Michael Eberon', src: './assets/media/avatars/300-11.jpg' },
      { name: 'Susan Redwood', initials: 'S', state: 'primary' },
      { name: 'Melody Macy', src: './assets/media/avatars/300-2.jpg' },
      { name: 'Perry Matthew', initials: 'P', state: 'danger' },
      { name: 'Barry Walter', src: './assets/media/avatars/300-12.jpg' },
    ];
  }
}

<!--begin::Card widget 7-->
<div class="card card-flush" [ngClass]="cssClass">
  <!--begin::Header-->
  <div class="card-header pt-5">
    <!--begin::Title-->
    <div class="card-title d-flex flex-column">
      <!--begin::Amount-->
      <span class="fs-2hx fw-bold text-gray-900 me-2 lh-1 ls-n2">{{stats}}</span>
      <!--end::Amount-->

      <!--begin::Subtitle-->
      <span class="text-gray-500 pt-1 fw-semibold fs-6">{{description}}</span>
      <!--end::Subtitle-->
    </div>
    <!--end::Title-->
  </div>
  <!--end::Header-->

  <!--begin::Card body-->
  <div class="card-body d-flex flex-column justify-content-end pe-0">
    <!--begin::Title-->
    <span class="fs-6 fw-bolder text-gray-800 d-block mb-2">Today’s Heroes</span>
    <!--end::Title-->

    <!--begin::Users group-->
    <div class="symbol-group symbol-hover flex-nowrap">
      <div *ngFor="let item of items" class="symbol symbol-35px symbol-circle" data-bs-toggle="tooltip"
        [title]="item.name">
        <ng-container *ngIf="item.src">
          <img alt="Pic" [src]="item.src" />
        </ng-container>
        <ng-container *ngIf="!item.src">
          <span class="symbol-label fw-bold"
            [ngClass]="'bg-' + item.state + ' ' + 'text-inverse-' + item.state">{{item.initials}}</span>
        </ng-container>

      </div>
      <a href="#" class="symbol symbol-35px symbol-circle">
        <span class="symbol-label fs-8 fw-bold" [ngClass]="'bg-' + labelColor"
          [ngClass]="'text-' + textColor">+42</span>
      </a>
    </div>
    <!--end::Users group-->
  </div>
  <!--end::Card body-->
</div>
<!--end::Card widget 7-->

// metronic_react_v8.2.3/react/metronic_react_v8.2.3_demo6/src/_metronic/partials/widgets/_new/cards/CardsWidget7.tsx

import clsx from 'clsx'
import {toAbsoluteUrl} from '../../../../helpers'

type Props = {
  className: string
  description: string
  icon: boolean
  stats: number
  labelColor: string
  textColor: string
}

const items: Array<{
  name: string
  initials?: string
  src?: string
  state?: string
}> = [
  {name: 'Alan Warden', initials: 'A', state: 'warning'},
  {name: 'Michael Eberon', src: toAbsoluteUrl('media/avatars/300-11.jpg')},
  {name: 'Susan Redwood', initials: 'S', state: 'primary'},
  {name: 'Melody Macy', src: toAbsoluteUrl('media/avatars/300-2.jpg')},
  {name: 'Perry Matthew', initials: 'P', state: 'danger'},
  {name: 'Barry Walter', src: toAbsoluteUrl('media/avatars/300-12.jpg')},
]

const CardsWidget7 = ({className, description, stats, labelColor, textColor}: Props) => (
  <div className={`card card-flush ${className}`}>
    <div className='card-header pt-5'>
      <div className='card-title d-flex flex-column'>
        <div className='card-title d-flex flex-column'>
          <span className='fs-2hx fw-bold text-gray-900 me-2 lh-1 ls-n2'>{stats}</span>
          <span className='text-gray-500 pt-1 fw-semibold fs-6'>{description}</span>
        </div>
      </div>
    </div>
    <div className='card-body d-flex flex-column justify-content-end pe-0'>
      <span className='fs-6 fw-bolder text-gray-800 d-block mb-2'>Today’s Heroes</span>
      <div className='symbol-group symbol-hover flex-nowrap'>
        {items.map((item, index) => (
          <div
            className='symbol symbol-35px symbol-circle'
            data-bs-toggle='tooltip'
            title={item.name}
            key={`cw7-item-${index}`}
          >
            {item.src && <img alt='Pic' src={item.src} />}
            {item.state && item.initials && (
              <span
                className={clsx(
                  'symbol-label fw-bold',
                  'bg-' + item.state,
                  'text-inverse-' + item.state
                )}
              >
                {item.initials}
              </span>
            )}
          </div>
        ))}

        <a href='#' className='symbol symbol-35px symbol-circle'>
          <span
            className={clsx('symbol-label fs-8 fw-bold', 'bg-' + labelColor, 'text-' + textColor)}
          >
            +42
          </span>
        </a>
      </div>
    </div>
  </div>
)
export {CardsWidget7}
